import { ProposedAction } from './types';

/**
 * Action parsing for the agent loop. Follows the proven `__aether_question`
 * pattern from messageParse.ts: the model's ENTIRE reply should be one flat
 * JSON object carrying a marker key, and parsing is tolerant of prose noise,
 * fences, and trailing commas because small models emit near-miss JSON.
 *
 * Only text generated BY the model is ever parsed for actions. Tool outputs,
 * web text, documents, and memories are scrubbed of the marker before they can
 * appear inside any prompt (see prompts.ts), so untrusted content can never
 * mint an action.
 */
export const ACTION_MARKER = '__aether_action';

function parseJsonTolerant(slice: string): unknown {
  try {
    return JSON.parse(slice);
  } catch {
    try {
      return JSON.parse(slice.replace(/,\s*([}\]])/g, '$1'));
    } catch {
      return null;
    }
  }
}

const MAX_ARG_CHARS = 4000;
const MAX_ARGS = 6;

function validateAction(obj: unknown): ProposedAction | null {
  if (!obj || typeof obj !== 'object') return null;
  const a = obj as Record<string, unknown>;
  const flagged = a[ACTION_MARKER] === true || a[ACTION_MARKER] === 'true';
  if (!flagged || typeof a.tool !== 'string' || !a.tool.trim()) return null;
  const args: Record<string, string> = {};
  const raw = a.args;
  if (raw && typeof raw === 'object' && !Array.isArray(raw)) {
    let count = 0;
    for (const [k, v] of Object.entries(raw as Record<string, unknown>)) {
      if (count >= MAX_ARGS) break;
      if (typeof v === 'string') args[k] = v.slice(0, MAX_ARG_CHARS);
      else if (typeof v === 'number' || typeof v === 'boolean') args[k] = String(v);
      else continue;
      count++;
    }
  }
  return { tool: a.tool.trim(), args };
}

/**
 * Extract the first valid action object from model output. Same successive
 * closing-brace scan messageParse uses — robust against braces inside arg
 * strings without a stateful scanner. Returns null when nothing parses; the
 * kernel treats that as a malformed step (retry once, then degrade).
 */
export function parseAction(text: string): ProposedAction | null {
  const markerIdx = text.indexOf(ACTION_MARKER);
  if (markerIdx === -1) return null;
  const start = text.lastIndexOf('{', markerIdx);
  if (start === -1) return null;
  let end = text.indexOf('}', markerIdx);
  while (end !== -1) {
    // Nested args object means the first '}' closes args, the next closes the
    // action — the scan naturally reaches it.
    const action = validateAction(parseJsonTolerant(text.slice(start, end + 1)));
    if (action) return action;
    end = text.indexOf('}', end + 1);
  }
  return null;
}

/** Stable hash of an action for repeat/loop detection. */
export function actionKey(a: ProposedAction): string {
  const args = Object.keys(a.args).sort().map((k) => `${k}=${a.args[k].trim().toLowerCase()}`);
  return `${a.tool}|${args.join('&')}`;
}

/**
 * Rescue check for output that names finish but failed to parse (truncated
 * JSON, stray prose). Only consulted AFTER parseAction returned null — a
 * finish intent must never be lost to formatting, because the kernel owns the
 * final answer anyway.
 */
export function looksLikeFinish(text: string): boolean {
  return /"tool"\s*:\s*"finish"/.test(text);
}

/** Normalize a title/outline for equivalence checks ("Study Plan!" ≡ "study plan"). */
export function normalizeKey(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}
